# Generated by Django 4.2.7 on 2023-11-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, verbose_name='Бренд')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('chipset', models.CharField(max_length=255, verbose_name='Чипсет')),
                ('socket', models.CharField(max_length=50, verbose_name='Сокет')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Материнская плата',
                'verbose_name_plural': 'Материнские платы',
            },
        ),
    ]
