# Generated by Django 4.2.7 on 2023-11-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_motherboard_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboard',
            name='photo',
            field=models.FileField(null=True, upload_to='img/'),
        ),
    ]
