# Generated by Django 4.2.7 on 2023-11-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_motherboard_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motherboard',
            options={'get_latest_by': 'id', 'verbose_name': 'Материнская плата', 'verbose_name_plural': 'Материнские платы'},
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='photo',
            field=models.FileField(null=True, upload_to='img/', verbose_name='Фото'),
        ),
    ]
